language: node_js
os: linux
sudo: required
dist: trusty
node_js:
  - "7"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before script:
  - export VFB_REPO=$(echo ${TRAVIS_REPO_SLUG##*/} | awk '{gsub(/\-/,"_",$0);gsub(/\./,"_",$0);print toupper($0)}')
  - export REPO=$(echo ${TRAVIS_REPO_SLUG} | awk '{gsub(/\./,"_",$0);print tolower($0)}')
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
script:
  - echo -e "travis_fold:start:docker-build"
  - travis_wait 190 docker build -t $REPO:$COMMIT .
  - echo -e "travis_fold:end:docker-build"
  - echo -e "travis_fold:start:NBLAST-boot"
  - travis_wait 190 docker run -d -ti --name test -p 80:80 -p 8004:8004 -p 443:443 $REPO:$COMMIT
  - travis_wait 12 sleep 2m
  - docker logs test 
  - travis_wait 12 sleep 2m
  - docker logs --since 3m test 
  - echo -e "travis_fold:end:NBLAST-boot"
  - travis_wait 60 curl -sSf http://localhost/ocpu/library/flycircuit/R/
  - docker logs --since 2m test 

after_success:
  - cd $TRAVIS_BUILD_DIR
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO:$TAG
