#!/usr/bin/env Rscript

.libPaths()
.libPaths( c( .libPaths(), "/usr/local/lib/opencpu/site-library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/site-library") )
.libPaths()
options(flycircuit.datadir="/data")
options(rgl.useNULL=TRUE)
if (!require("Rcpp")) install.packages("Rcpp",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("igraph")) install.packages("igraph",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("brew")) install.packages("brew",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("git2r")) install.packages("git2r",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("memoise")) install.packages("memoise",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("jsonlite")) install.packages("jsonlite",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("devtools")) install.packages("devtools",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("ggplot2")) install.packages("ggplot2",repos="https://cloud.r-project.org/", dependencies = TRUE)
if (!require("rgl")) install.packages("rgl",repos="https://cloud.r-project.org/", dependencies = TRUE)
devtools::install_github("jefferis/nat", force=TRUE, dependencies=TRUE)
devtools::install_github("jefferis/vfbr", force=TRUE, dependencies=TRUE)
devtools::install_github("jefferis/flycircuit", force=TRUE, dependencies=TRUE)
devtools::install_github("jefferis/flynblastscores", force=TRUE, dependencies=TRUE)
