## Rprofile for OpenCPU cloud server.
.libPaths()
.libPaths( c( .libPaths(), "/usr/local/lib/opencpu/site-library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/site-library") )
.libPaths()
options(flycircuit.datadir="/data")
options(rgl.useNULL=TRUE)
if (!require("Rcpp")) install.packages("Rcpp",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("igraph")) install.packages("igraph",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("brew")) install.packages("brew",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("git2r")) install.packages("git2r",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("memoise")) install.packages("memoise",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("jsonlite")) install.packages("jsonlite",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("devtools")) install.packages("devtools",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("ggplot2")) install.packages("ggplot2",repos="http://cran.rstudio.com/", dependencies = TRUE)
if (!require("rgl")) install.packages("rgl",repos="http://cran.rstudio.com/", dependencies = TRUE)

