## Rprofile for OpenCPU cloud server.

.libPaths()
.libPaths( c( "/usr/local/lib/R/site-library") )
.libPaths( c( .libPaths(), "/usr/lib/R/library") )
.libPaths( c( .libPaths(), "/usr/lib/R/site-library") )
.libPaths( c( .libPaths(), "/usr/local/lib/opencpu/site-library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/library") )
.libPaths( c( .libPaths(), "/usr/lib/opencpu/site-library") )
.libPaths()
options(flycircuit.datadir="/usr/local/lib/R/site-library/flycircuit/data")
options(rgl.useNULL=TRUE)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = TRUE)
if (!require("Rcpp")) install.packages("Rcpp",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("igraph")) install.packages("igraph",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("brew")) install.packages("brew",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("git2r")) install.packages("git2r",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("memoise")) install.packages("memoise",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("jsonlite")) install.packages("jsonlite",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("devtools")) install.packages("devtools",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("ggplot2")) install.packages("ggplot2",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("rgl")) install.packages("rgl",repos="http://cran.rstudio.com/", dependencies = TRUE, lib="/usr/local/lib/R/site-library")
if (!require("nat")) devtools::install_github("jefferis/nat", dependencies=TRUE, lib="/usr/local/lib/R/site-library")
if (!require("vfbr")) devtools::install_github("jefferis/vfbr", dependencies=TRUE, lib="/usr/local/lib/R/site-library")
if (!require("flycircuit")) devtools::install_github("jefferis/flycircuit", dependencies=TRUE, lib="/usr/local/lib/R/site-library")
if (!require("flynblastscores")) devtools::install_github("jefferis/flynblastscores", dependencies=TRUE, lib="/usr/local/lib/R/site-library")
